/*
Highly divisible triangular number
 
Problem 12

The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?

*/

#include <stdio.h>
#include <math.h>

int countDivisors(int n);
// Function to print the divisors 


/* Driver program to test above function */
int main() 
{ 
	int triangle = 0;
	for (int i = 1; i < 10000; i++)
    {
        triangle +=i;
        printf("%d triangle number is: %d\n",i,triangle);
        if (countDivisors(i) > 500)
        {
            printf("500 den fazla boleni olan triangle sayi: %d",triangle);
            i = 10000;
        }
        
    }
     
	return 0; 
} 

int countDivisors(int n) 
{ 
	// Note that this loop runs till square root
    int count = 0; 
	for (int i=1; i<=sqrt(n); i++) 
	{ 
		if (n%i == 0) 
		{ 
			// If divisors are equal, print only one 
			if (n/i == i) 
				count+=2; 

			else // Otherwise print both 
				count++; 
		} 
	}
    return count; 
}

